### ISSUE TITLE
Problem with the spin() Method

### ISSUE THREAD

**Issue by Marvins13** [Roguyt/node-epicsgg#78]
I am trying to implement the spin method, but I keep getting the following error message.

`
(node:8728) UnhandledPromiseRejectionWarning: Error: The spinner has changed.
    at BaseClient.<anonymous> (C:\server\epicsgg\node_modules\node-epicsgg\lib\client\BaseClient.js:191:35)
    at Generator.throw (<anonymous>)
    at rejected (C:\server\epicsgg\node_modules\node-epicsgg\lib\client\BaseClient.js:7:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

Everything else seems to work.

**Comment by Roguyt** [comment]
You need to update the spinnerId that you are using.
